[toolchain]
channel = "1.88.0"
components = ["rustfmt", "rust-src"]
profile = "minimal"

#rzup show
#Installed components:
#--------------------
#
#cargo-risczero
#* 2.0.2
#
#cpp
#* 2024.1.5
#
#r0vm
#* 2.0.2
#
#rust
#* 1.88.0
#
#rzup home: /Users/sonak/.risc0