// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant IS_EVEN_ID = bytes32(0x36b329656652848120f15432d4a070c34fa8bcd1a84b37b39c3ca542d8dcac9e);
    bytes32 public constant VERIFY_AR_ID = bytes32(0xf473702bcd04a4d6f4464087f127b79786f9a4204e5440be39e924e8d6e29b8b);
}
