// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant IS_EVEN_ID = bytes32(0xcca51a54e35c48e782fcb8e1eeec2ed5fe9b8a92faeab4d10c18ae774253f9b5);
    bytes32 public constant VERIFY_AR_ID = bytes32(0x829e25d7f89b0eaa7d3bfd399860394b4b5817b2ae10f31eba3b52dde11d74d6);
}
