// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant IS_EVEN_ID = bytes32(0x8acc988f6c4d4ed7613e5e35a4f877a6bd1de9f9845951d1bf4db00cac2e0e23);
    bytes32 public constant VERIFY_AR_ID = bytes32(0x78841dd08fac7fac75474eda4f75cf34442399f922c124d129152ee5e231fbef);
}
