---
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8545:8545"
    command: anvil
    healthcheck:
      test: ["CMD-SHELL", "cast block-number --rpc-url http://localhost:8545 >/dev/null 2>&1 || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 15
  
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_local
    restart: unless-stopped
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
    tmpfs:
      - /data/ipfs

  remote-attestation: 
    build:
      context: ..
      dockerfile: docker/Dockerfile_Remote_Attestation
    image: sonak53/dfl-ra:latest
    container_name: remote-attestation
    platform: linux/amd64
    depends_on:
      anvil:
        condition: service_healthy
    environment:
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      INITIAL_GM_CID: ${INITIAL_GM_CID}
    command: ["/dfl/remote_attestation/starter_docker.sh"]

  VM-0:
    build:
      context: ..
      dockerfile: docker/Dockerfile_Worker
    image: sonak53/dfl-server-img:latest
    platform: linux/amd64
    depends_on:
      remote-attestation:
        condition: service_completed_successfully
    container_name: ${W0_ACCOUNT_ADDRESS}
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      PINATA_JWT: ${PINATA_JWT}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      KUBO_API: ${KUBO_API}
      KUBO_GATEWAY: ${KUBO_GATEWAY}
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      REGISTRY_ADDRESS: ${REGISTRY_ADDRESS}
      AGGREGATOR_ADDRESS: ${AGGREGATOR_ADDRESS}
      GM_STORAGE_ADDRESS: ${GM_STORAGE_ADDRESS}
      SEPOLIA_RPC_URL: ${RPC_URL}
      ACCOUNT_ADDRESS: ${W0_ACCOUNT_ADDRESS}
      PRIVATE_KEY: ${W0_PRIVATE_KEY}
      DEVICE_ID: ${W0_DEVICE_ID}
    #volumes:
    #  - .cloud_setup/ansible/config/training_data/train-images-0.idx3-ubyte:/dfl/node_server/data/train-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/training_data/train-labels-0.idx1-ubyte:/dfl/node_server/data/train-labels.idx1-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-images.idx3-ubyte:/dfl/node_server/data/t10k-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-labels.idx1-ubyte:/dfl/node_server/data/t10k-labels.idx1-ubyte
    command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-0.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
        cp /dfl/config/training_data/train-labels-0.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
        cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
        cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte && \
        exec node /dfl/node_server/dist/server.js"]
      #command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-0.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
    #    cp /dfl/config/training_data/train-labels-0.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
    #    cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
    #    cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte"]
  #  command: ["/opt/dfl/start.exe","server"]

  VM-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile_Worker
    image: sonak53/dfl-server-img:latest
    platform: linux/amd64
    depends_on:
      remote-attestation:
        condition: service_completed_successfully
    container_name: ${W1_ACCOUNT_ADDRESS}
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      PINATA_JWT: ${PINATA_JWT}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      KUBO_API: ${KUBO_API}
      KUBO_GATEWAY: ${KUBO_GATEWAY}
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      REGISTRY_ADDRESS: ${REGISTRY_ADDRESS}
      AGGREGATOR_ADDRESS: ${AGGREGATOR_ADDRESS}
      GM_STORAGE_ADDRESS: ${GM_STORAGE_ADDRESS}
      SEPOLIA_RPC_URL: ${RPC_URL}
      ACCOUNT_ADDRESS: ${W1_ACCOUNT_ADDRESS}
      PRIVATE_KEY: ${W1_PRIVATE_KEY}
      DEVICE_ID: ${W1_DEVICE_ID}
    #volumes:
    #  - .cloud_setup/ansible/config/training_data/train-images-1.idx3-ubyte:/dfl/node_server/data/train-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/training_data/train-labels-1.idx1-ubyte:/dfl/node_server/data/train-labels.idx1-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-images.idx3-ubyte:/dfl/node_server/data/t10k-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-labels.idx1-ubyte:/dfl/node_server/data/t10k-labels.idx1-ubyte
    command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-1.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
        cp /dfl/config/training_data/train-labels-1.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
        cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
        cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte && \
        exec node /dfl/node_server/dist/server.js"]

  VM-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile_Worker
    image: sonak53/dfl-server-img:latest
    platform: linux/amd64
    depends_on:
      remote-attestation:
        condition: service_completed_successfully
    container_name: ${W2_ACCOUNT_ADDRESS}
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      PINATA_JWT: ${PINATA_JWT}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      KUBO_API: ${KUBO_API}
      KUBO_GATEWAY: ${KUBO_GATEWAY}
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      REGISTRY_ADDRESS: ${REGISTRY_ADDRESS}
      AGGREGATOR_ADDRESS: ${AGGREGATOR_ADDRESS}
      GM_STORAGE_ADDRESS: ${GM_STORAGE_ADDRESS}
      SEPOLIA_RPC_URL: ${RPC_URL}
      ACCOUNT_ADDRESS: ${W2_ACCOUNT_ADDRESS}
      PRIVATE_KEY: ${W2_PRIVATE_KEY}
      DEVICE_ID: ${W2_DEVICE_ID}
    #volumes:
    #  - .cloud_setup/ansible/config/training_data/train-images-2.idx3-ubyte:/dfl/node_server/data/train-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/training_data/train-labels-2.idx1-ubyte:/dfl/node_server/data/train-labels.idx1-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-images.idx3-ubyte:/dfl/node_server/data/t10k-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-labels.idx1-ubyte:/dfl/node_server/data/t10k-labels.idx1-ubyte
    command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-2.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
      cp /dfl/config/training_data/train-labels-2.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
      cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
      cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte && \
      exec node /dfl/node_server/dist/server.js"]

  VM-3:
    build:
      context: ..
      dockerfile: docker/Dockerfile_Worker
    image: sonak53/dfl-server-img:latest
    platform: linux/amd64
    depends_on:
      remote-attestation:
        condition: service_completed_successfully
    container_name: ${W3_ACCOUNT_ADDRESS}
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      PINATA_JWT: ${PINATA_JWT}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      KUBO_API: ${KUBO_API}
      KUBO_GATEWAY: ${KUBO_GATEWAY}
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      REGISTRY_ADDRESS: ${REGISTRY_ADDRESS}
      AGGREGATOR_ADDRESS: ${AGGREGATOR_ADDRESS}
      GM_STORAGE_ADDRESS: ${GM_STORAGE_ADDRESS}
      SEPOLIA_RPC_URL: ${RPC_URL}
      ACCOUNT_ADDRESS: ${W3_ACCOUNT_ADDRESS}
      PRIVATE_KEY: ${W3_PRIVATE_KEY}
      DEVICE_ID: ${W3_DEVICE_ID}
    #volumes:
    #  - .cloud_setup/ansible/config/training_data/train-images-3.idx3-ubyte:/dfl/node_server/data/train-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/training_data/train-labels-3.idx1-ubyte:/dfl/node_server/data/train-labels.idx1-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-images.idx3-ubyte:/dfl/node_server/data/t10k-images.idx3-ubyte
    #  - .cloud_setup/ansible/config/test_data/t10k-labels.idx1-ubyte:/dfl/node_server/data/t10k-labels.idx1-ubyte
    command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-3.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
        cp /dfl/config/training_data/train-labels-3.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
        cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
        cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte && \
        exec node /dfl/node_server/dist/server.js"]



    #command: ["/bin/sh", "-c", "cp /dfl/config/training_data/train-images-0.idx3-ubyte /dfl/node_server/data/train-images.idx3-ubyte && \
    #    cp /dfl/config/training_data/train-labels-0.idx1-ubyte /dfl/node_server/data/train-labels.idx1-ubyte && \
    #    cp /dfl/config/test_data/t10k-images.idx3-ubyte /dfl/node_server/data/t10k-images.idx3-ubyte && \
    #    cp /dfl/config/test_data/t10k-labels.idx1-ubyte /dfl/node_server/data/t10k-labels.idx1-ubyte"]
  #  command: ["/opt/dfl/start.exe","server"]