---
services:
  smart-contracts: 
    build:
      context: ..
      dockerfile: docker/Dockerfile_Smart_Contracts
    #image: sonak53/dfl-ra:latest_10
    container_name: smart-contracts
    platform: linux/amd64  
    environment:
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      DOCKER: ${DOCKER}
      INITIAL_GM_CID: ${INITIAL_GM_CID}
      INITIAL_GM_SIG_CID: ${INITIAL_GM_SIG_CID}
      INITIAL_GM_SIGNER_ADDRESS: ${INITIAL_GM_SIGNER_ADDRESS}
      #RUST_LOG: debug
    command: ["/dfl/remote_attestation/starter_docker.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock