#FROM gcc:latest
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential g++ make libssl-dev libzmq3-dev libeigen3-dev libcrypto++-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY neural_network/src/ ./src/
COPY docker/Makefile ./
COPY neural_network/data/ ./data/
COPY neural_network/config/ ./config/

RUN make clean || true
RUN make start

RUN mkdir -p /out
RUN cp ./start.exe /out/

#CMD ["sleep", "infinity"]

# Compile with system OpenSSL (libssl-dev) and export to /out (mount a host dir: -v "$PWD/linux_out:/out")
