---
- name: prepare
  hosts: azure_vms
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Optional: cache valid for 1 hour to avoid redundant updates

    - name: Run apt-get upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install ZeroMQ library
      ansible.builtin.apt:
        name: libzmq3-dev
        state: present
        update_cache: yes

    - name: Efficiently copy src folder to VMs
      ansible.builtin.synchronize:
        src: "../../node_code/"
        dest: "./training/"
        recursive: yes
