services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
    working_dir: /anvil
    ports:
      - "8545:8545"
    entrypoint: 
      - anvil
    command:
      - --accounts
      - "20"
    healthcheck:
      test: ["CMD-SHELL", "cast block-number --rpc-url http://localhost:8545 >/dev/null 2>&1 || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 15
  
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_local
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    tmpfs:
      - /data/ipfs
