services:
  remote-attestation: 
    image: sonak53/dfl-ra:latest_2
    container_name: remote-attestation
    platform: linux/amd64
    environment:
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
      IPFS_PROVIDER: ${IPFS_PROVIDER}
      INITIAL_GM_CID: ${INITIAL_GM_CID}
      DOCKER: ${DOCKER}
    command: ["/dfl/smart_contracts/starter_docker.sh"]
